name: Build Galactic Game

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pygame PyOpenGL PyOpenGL-accelerate numpy pyinstaller
    
    - name: Build executable
      run: |
        pyinstaller --onefile --name "GalacticGame" main.py
    
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: GalacticGame-Linux
        path: dist/
