name: Build Galactic Game

on:
  push:
    tags: ['v*']
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pygame PyOpenGL PyOpenGL-accelerate numpy pyinstaller
    
    - name: Build executable
      run: |
        pyinstaller --onefile --windowed --name "GalacticGame" main.py
    
    - name: Upload Windows artifact
      uses: actions/upload-artifact@v4
      with:
        name: GalacticGame-Windows
        path: dist/
        retention-days: 30

  build-linux:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-ttf-dev
        sudo apt-get install -y libgl1-mesa-dev libglu1-mesa-dev
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pygame PyOpenGL PyOpenGL-accelerate numpy pyinstaller
    
    - name: Build executable
      run: |
        pyinstaller --onefile --name "GalacticGame" main.py
        chmod +x dist/GalacticGame
    
    - name: Upload Linux artifact
      uses: actions/upload-artifact@v4
      with:
        name: GalacticGame-Linux
        path: dist/
        retention-days: 30
